version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    #restart: unless-stopped
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes: 
      - dbdata:/var/lib/mysql
    #command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
    ports:
      - "33060:3306"

  wordpress:
    depends_on: 
      - db
    image: wordpress:5.2-php7.2-fpm
    container_name: wordpress
    #restart: unless-stopped
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      PHP_ENV: DEV
    working_dir: /var/www/html/wordpress
    volumes:
      - "./website/wordpress:/var/www/html/wordpress"
      - "./php-conf/upload.ini:/usr/local/etc/php/conf.d/upload.ini"
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:stable
    container_name: webserver
    #restart: unless-stopped
    restart: always
    ports:
      - "8000:80"
    volumes:
      - "./website:/var/www/html"
      - "./nginx-conf:/etc/nginx/conf.d"
      - "./php-conf/php.ini:/etc/php.ini"
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge
